# Generated by Django 5.2.17 on 2026-09-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('institutional', 'Institutional Collaboration'), ('individual', 'Individual Collaboration')], default='institutional', max_length=20)),
                ('logo_url', models.URLField(default='https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400&q=80', max_length=500)),
                ('blurb', models.TextField()),
                ('website_url', models.URLField(blank=True, default='#', max_length=500)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Collaborations',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('executive', 'Executive Team'), ('advisory', 'Advisory Board'), ('general', 'General Members')], default='executive', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80', max_length=500)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_visitors',
            field=models.IntegerField(default=0),
        ),
    ]
