# Generated by Django 5.2.17 on 2026-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='helpdesk_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
