# Generated by Django 6.0.4 on 2026-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_resource_category_alter_resource_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
