# Generated by Django 6.0.4 on 2026-09-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_sitesettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_image_url',
        ),
    ]
