# Generated by Django 5.2.17 on 2026-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('date_str', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(default='Advocacy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Photo Gallery',
            },
        ),
        migrations.CreateModel(
            name='GatedDownloadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('resource_title', models.CharField(max_length=255)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gated Download Leads',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=150)),
                ('contact_info', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=100)),
                ('incident_type', models.CharField(default='Urgent Support', max_length=100)),
                ('details', models.TextField()),
                ('priority', models.CharField(default='High', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_str', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(default='News & Updates', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News & Updates',
            },
        ),
        migrations.CreateModel(
            name='PopupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('link_url', models.CharField(default='#', max_length=500)),
                ('link_text', models.CharField(default='Learn More', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Popup Banners',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('base_city', models.CharField(max_length=100)),
                ('coords_lat', models.FloatField()),
                ('coords_lng', models.FloatField()),
                ('coordinators_count', models.IntegerField(default=10)),
                ('helpline_phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('active_cases', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('long_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Document', max_length=50)),
                ('format', models.CharField(default='PDF', max_length=20)),
                ('file_size', models.CharField(default='2.0 MB', max_length=50)),
                ('file_url', models.CharField(default='#', max_length=500)),
                ('is_gated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincial_networks', models.IntegerField(default=7)),
                ('monitored_defenders', models.CharField(default='1,200+', max_length=50)),
                ('resolved_cases', models.CharField(default='150+', max_length=50)),
                ('total_visitors', models.IntegerField(default=14230)),
            ],
            options={
                'verbose_name_plural': 'Statistics Metrics',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('embed_url', models.URLField(max_length=500)),
                ('category', models.CharField(default='Documentary', max_length=50)),
                ('date_str', models.CharField(max_length=50)),
            ],
        ),
    ]
