# Generated by Django 5.2.17 on 2026-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Flashes / Ticker',
                'ordering': ['order_index', '-created_at'],
            },
        ),
    ]
