# Generated by Django 5.2.17 on 2026-09-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_newsflash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('session_key', models.CharField(blank=True, default='', max_length=255)),
                ('first_visited', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Unique Visitors Log',
            },
        ),
    ]
