# Generated by Django 5.2.17 on 2026-09-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_uniquevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='districts_count',
            field=models.IntegerField(default=10),
        ),
    ]
