# Generated by Django 6.0.4 on 2026-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_province_districts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='collaborations/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='popupconfig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popups/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='logo_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400&q=80', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='popupconfig',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80', max_length=500, null=True),
        ),
    ]
