# Generated by Django 6.0.4 on 2026-09-04 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_blog_image_collaboration_logo_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='gateddownloadlead',
            options={'ordering': ['-downloaded_at'], 'verbose_name_plural': 'Gated Download Leads'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'News & Updates'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_str',
        ),
        migrations.RemoveField(
            model_name='gateddownloadlead',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_str',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_str',
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gateddownloadlead',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='main_app.resource'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gateddownloadlead',
            name='resource_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='main_app.province'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='main_app.province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='active_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='coordinators_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='province',
            name='districts_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='monitored_defenders',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='stats',
            name='provincial_networks',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='stats',
            name='resolved_cases',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uniquevisitor',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
