# Generated by Django 6.0.4 on 2026-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_blog_options_alter_gateddownloadlead_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField(blank=True, default='To establish a society where human rights are respected, protected, and fulfilled for all.')),
                ('mission_text', models.TextField(blank=True, default='To protect and empower frontline human rights defenders across Nepal through legal support, capacity building, and national coordination.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('support_us_text', models.TextField(blank=True, default='Your support enables us to provide 24/7 legal aid to defenders at risk.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
