# Generated by Django 6.0.4 on 2026-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Report', 'Report'), ('Publication', 'Publication'), ('By-Law', 'By-Law'), ('Other', 'Other')], default='Report', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, default='0 KB', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(blank=True, default='PDF', max_length=20),
        ),
    ]
