# Generated by Django 6.0.4 on 2026-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_sitesettings_hero_image_sitesettings_hero_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receipt_image', models.ImageField(upload_to='contributions/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_us_text',
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(default='Document', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.CharField(default='2.0 MB', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(default='PDF', max_length=20),
        ),
    ]
