# Generated by Django 6.0.4 on 2026-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_supportcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_name',
            field=models.CharField(default='HRD Forum Nepal', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_no',
            field=models.CharField(default='0011223344556677', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_branch',
            field=models.CharField(default='Kathmandu Main', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(default='Nepal Bank Limited', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_qr_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
