# Generated by Django 6.0.4 on 2026-09-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_sitesettings_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bank_qr_image_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image_url',
        ),
    ]
