# Generated by Django 6.0.4 on 2026-09-22 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_sitesettings_bank_qr_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to='updates/documents/')),
                ('description', models.TextField(blank=True, default='')),
                ('is_urgent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Organizational Updates',
                'ordering': ['-date_posted', '-id'],
            },
        ),
    ]
